export const runtimeSchemaStatements = [
  `CREATE TABLE IF NOT EXISTS members (
    id text PRIMARY KEY NOT NULL,
    site_user_id text,
    password_hash text,
    email text NOT NULL,
    name text NOT NULL,
    role text DEFAULT 'member' NOT NULL,
    research_field text DEFAULT '待补充' NOT NULL,
    status text DEFAULT 'invited' NOT NULL,
    oauth_credential_version integer DEFAULT 0 NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_seen_at text
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id text PRIMARY KEY NOT NULL,
    member_id text NOT NULL REFERENCES members(id),
    token_hash text NOT NULL,
    expires_at text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id text PRIMARY KEY NOT NULL,
    public_code text,
    title text NOT NULL,
    summary text NOT NULL,
    field text NOT NULL,
    owner_member_id text NOT NULL REFERENCES members(id),
    status text DEFAULT '待分配' NOT NULL,
    review_scope text NOT NULL,
    ai_disclosure text DEFAULT '未使用生成式 AI' NOT NULL,
    recommended_journals text DEFAULT '' NOT NULL,
    ai_submission_advice text DEFAULT '' NOT NULL,
    visibility text DEFAULT 'internal' NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS upload_tokens (
    id text PRIMARY KEY NOT NULL,
    member_id text NOT NULL REFERENCES members(id),
    name text NOT NULL,
    token_hash text NOT NULL,
    token_prefix text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at text,
    expires_at text NOT NULL,
    revoked_at text
  )`,
  `CREATE TABLE IF NOT EXISTS project_tags (
    id text PRIMARY KEY NOT NULL,
    project_id text NOT NULL REFERENCES projects(id),
    name text NOT NULL,
    normalized_name text NOT NULL,
    created_by_member_id text NOT NULL REFERENCES members(id),
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_likes (
    id text PRIMARY KEY NOT NULL,
    project_id text NOT NULL REFERENCES projects(id),
    member_id text NOT NULL REFERENCES members(id),
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tag_likes (
    id text PRIMARY KEY NOT NULL,
    tag_id text NOT NULL REFERENCES project_tags(id),
    member_id text NOT NULL REFERENCES members(id),
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS project_versions (
    id text PRIMARY KEY NOT NULL,
    project_id text NOT NULL REFERENCES projects(id),
    version_number integer DEFAULT 1 NOT NULL,
    artifact_kind text DEFAULT 'description' NOT NULL,
    file_name text NOT NULL,
    storage_key text NOT NULL,
    content_type text DEFAULT 'application/octet-stream' NOT NULL,
    size_bytes integer NOT NULL,
    uploaded_by_member_id text NOT NULL REFERENCES members(id),
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS assignments (
    id text PRIMARY KEY NOT NULL,
    project_id text NOT NULL REFERENCES projects(id),
    reviewer_member_id text NOT NULL REFERENCES members(id),
    assigned_by_member_id text NOT NULL REFERENCES members(id),
    scope text NOT NULL,
    due_date text,
    status text DEFAULT '待接受' NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at text
  )`,
  `CREATE TABLE IF NOT EXISTS reviews (
    id text PRIMARY KEY NOT NULL,
    assignment_id text NOT NULL UNIQUE REFERENCES assignments(id),
    verdict text NOT NULL,
    correctness text NOT NULL,
    reproducibility text NOT NULL,
    data_and_ethics text NOT NULL,
    major_issues text DEFAULT '' NOT NULL,
    minor_issues text DEFAULT '' NOT NULL,
    summary text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS download_logs (
    id text PRIMARY KEY NOT NULL,
    project_id text NOT NULL REFERENCES projects(id),
    version_id text NOT NULL REFERENCES project_versions(id),
    member_id text NOT NULL REFERENCES members(id),
    downloaded_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_clients (
    id text PRIMARY KEY NOT NULL,
    client_name text NOT NULL,
    redirect_uris text NOT NULL,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_authorization_codes (
    id text PRIMARY KEY NOT NULL,
    code_hash text NOT NULL,
    member_id text NOT NULL REFERENCES members(id),
    client_id text NOT NULL REFERENCES oauth_clients(id),
    redirect_uri text NOT NULL,
    resource text NOT NULL,
    scope text NOT NULL,
    code_challenge text NOT NULL,
    credential_version integer DEFAULT 0 NOT NULL,
    expires_at text NOT NULL,
    consumed_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_token_families (
    id text PRIMARY KEY NOT NULL,
    member_id text NOT NULL REFERENCES members(id),
    client_id text NOT NULL REFERENCES oauth_clients(id),
    credential_version integer NOT NULL,
    revoked_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_tokens (
    id text PRIMARY KEY NOT NULL,
    family_id text NOT NULL REFERENCES oauth_token_families(id),
    token_hash text NOT NULL,
    token_type text NOT NULL,
    member_id text NOT NULL REFERENCES members(id),
    client_id text NOT NULL REFERENCES oauth_clients(id),
    resource text NOT NULL,
    scope text NOT NULL,
    expires_at text NOT NULL,
    consumed_at text,
    revoked_at text,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS ai_access_logs (
    id text PRIMARY KEY NOT NULL,
    member_id text NOT NULL REFERENCES members(id),
    project_id text REFERENCES projects(id),
    version_id text REFERENCES project_versions(id),
    channel text DEFAULT 'chatgpt_mcp' NOT NULL,
    action text NOT NULL,
    material_kind text,
    outcome text NOT NULL,
    denial_reason text,
    project_code_snapshot text,
    project_title_snapshot text,
    file_name_snapshot text,
    created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_rate_limits (
    key text PRIMARY KEY NOT NULL,
    count integer DEFAULT 1 NOT NULL,
    expires_at text NOT NULL
  )`,
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_members_email ON members(email)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_members_site_user_id ON members(site_user_id)",
  "CREATE INDEX IF NOT EXISTS idx_members_status ON members(status)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_member ON sessions(member_id)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_upload_tokens_hash ON upload_tokens(token_hash)",
  "CREATE INDEX IF NOT EXISTS idx_upload_tokens_member ON upload_tokens(member_id)",
  "CREATE INDEX IF NOT EXISTS idx_upload_tokens_expiry ON upload_tokens(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_projects_field_status ON projects(field, status)",
  "CREATE INDEX IF NOT EXISTS idx_projects_owner ON projects(owner_member_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_project_tags_project_normalized ON project_tags(project_id, normalized_name)",
  "CREATE INDEX IF NOT EXISTS idx_project_tags_project ON project_tags(project_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_project_likes_project_member ON project_likes(project_id, member_id)",
  "CREATE INDEX IF NOT EXISTS idx_project_likes_project ON project_likes(project_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_tag_likes_tag_member ON tag_likes(tag_id, member_id)",
  "CREATE INDEX IF NOT EXISTS idx_tag_likes_tag ON tag_likes(tag_id)",
  "CREATE INDEX IF NOT EXISTS idx_versions_project_created ON project_versions(project_id, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_assignments_project_reviewer ON assignments(project_id, reviewer_member_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_assignments_project_active ON assignments(project_id) WHERE status IN ('待接受', '待审核')",
  "CREATE INDEX IF NOT EXISTS idx_assignments_reviewer_status ON assignments(reviewer_member_id, status)",
  "CREATE UNIQUE INDEX IF NOT EXISTS reviews_assignment_id_unique ON reviews(assignment_id)",
  "CREATE INDEX IF NOT EXISTS idx_download_logs_project_time ON download_logs(project_id, downloaded_at)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_clients_created ON oauth_clients(created_at)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_codes_hash ON oauth_authorization_codes(code_hash)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_codes_expiry ON oauth_authorization_codes(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_codes_client ON oauth_authorization_codes(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_families_member ON oauth_token_families(member_id)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_families_client ON oauth_token_families(client_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_tokens_hash ON oauth_tokens(token_hash)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_tokens_expiry ON oauth_tokens(expires_at)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_tokens_member ON oauth_tokens(member_id)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_tokens_family ON oauth_tokens(family_id)",
  "CREATE INDEX IF NOT EXISTS idx_ai_access_logs_project_time ON ai_access_logs(project_id, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_ai_access_logs_member_time ON ai_access_logs(member_id, created_at)",
  "CREATE INDEX IF NOT EXISTS idx_oauth_rate_limits_expiry ON oauth_rate_limits(expires_at)",
  "PRAGMA optimize",
] as const;
